export type {
  AntoineBase,
  AntoineFitReport,
  AntoineFitResultCompat,
  AntoineLoss,
  CalcVaporPressureOptions,
  CalcVaporPressureResult,
  CalcVaporPressureWithUnitsResult,
  EstimateFromFileOptions,
  EstimateOptions,
  FitAntoineOptions,
  OutlierReportItem,
  OutlierReportOptions,
  PressureUnit,
  RegressionPressureUnit,
  RegressionTemperatureUnit,
  TemperatureUnit,
} from "./types/antoine";
export type {
  GroupUnit,
  JobackAliasContributionMap,
  JobackCalcProp,
  JobackCategoryMap,
  JobackEstimatedProperties,
  JobackGroupCanonicalAlias,
  JobackGroupContributionFields,
  JobackGroupFieldName,
  JobackGroupInfoItem,
  JobackInputGroups,
  JobackProp,
  JobackSigma,
  JobackTableRow,
  JobackValidGroupData,
} from "./types/jb";
export { Antoine, AntoineError, calcVaporPressure, calcVaporPressureWithUnits, fitAntoine, loadExperimentalData } from "./core/antoine";
export { Joback, JobackError, calcJoback, calcJobackHeatCapacity, calcJobackProperties, listAvailableJobackGroups, loadJobackTable } from "./core/joback";
export {
  calcVaporPressure as calcVaporPressureLegacy,
  calcVaporPressureWithUnits as calcVaporPressureWithUnitsLegacy,
  estimateCoefficients,
  estimateCoefficientsFromExperimentalData,
  fitAntoine as fitAntoineFromTypedInputs,
} from "./docs/antoine";
export {
  jobackCalc,
  jobackHeatCapacityCalc,
  jobackPropCalc,
  jobackGroupContributionCategory,
  jobackGroupContributionIds,
  jobackGroupContributionInfo,
  jobackGroupContributionNames,
  joback_calc,
  joback_group_contribution_category,
  joback_group_contribution_ids,
  joback_group_contribution_info,
  joback_group_contribution_names,
  joback_heat_capacity_calc,
  joback_prop_calc,
} from "./docs/joback";
